//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.OrderStatusReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", ConfigurationName="OrderStatusReference.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since the operation getOrderStatusDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusDetails", ReplyAction="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/IService1/getOrderSta" +
            "tusDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1 getOrderStatusDetails(ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusDetails", ReplyAction="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/IService1/getOrderSta" +
            "tusDetailsResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1> getOrderStatusDetailsAsync(ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getOrderStatusTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusTypes", ReplyAction="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/IService1/getOrderSta" +
            "tusTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1 getOrderStatusTypes(ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusTypes", ReplyAction="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/IService1/getOrderSta" +
            "tusTypesResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1> getOrderStatusTypesAsync(ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private int queryTypeField;
        
        private string referenceNumberField;
        
        private System.Nullable<System.DateTime> statusTimeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
                this.RaisePropertyChanged("wsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
                this.RaisePropertyChanged("queryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> statusTimeStamp {
            get {
                return this.statusTimeStampField;
            }
            set {
                this.statusTimeStampField = value;
                this.RaisePropertyChanged("statusTimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatus[] orderStatusArrayField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatus", IsNullable=false)]
        public ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatus[] OrderStatusArray {
            get {
                return this.orderStatusArrayField;
            }
            set {
                this.orderStatusArrayField = value;
                this.RaisePropertyChanged("OrderStatusArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string purchaseOrderNumberField;
        
        private ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetail[] orderStatusDetailArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string purchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("purchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatusDetail", IsNullable=false)]
        public ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetail[] OrderStatusDetailArray {
            get {
                return this.orderStatusDetailArrayField;
            }
            set {
                this.orderStatusDetailArrayField = value;
                this.RaisePropertyChanged("OrderStatusDetailArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string factoryOrderNumberField;
        
        private ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetailStatusID statusIDField;
        
        private string statusNameField;
        
        private System.Nullable<System.DateTime> expectedShipDateField;
        
        private bool expectedShipDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expectedDeliveryDateField;
        
        private bool expectedDeliveryDateFieldSpecified;
        
        private ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondToRespondTo[] responseToArrayField;
        
        private string additionalExplanationField;
        
        private bool responseRequiredField;
        
        private bool responseRequiredFieldSpecified;
        
        private System.DateTime validTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string factoryOrderNumber {
            get {
                return this.factoryOrderNumberField;
            }
            set {
                this.factoryOrderNumberField = value;
                this.RaisePropertyChanged("factoryOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetailStatusID statusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("statusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string statusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
                this.RaisePropertyChanged("statusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> expectedShipDate {
            get {
                return this.expectedShipDateField;
            }
            set {
                this.expectedShipDateField = value;
                this.RaisePropertyChanged("expectedShipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedShipDateSpecified {
            get {
                return this.expectedShipDateFieldSpecified;
            }
            set {
                this.expectedShipDateFieldSpecified = value;
                this.RaisePropertyChanged("expectedShipDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> expectedDeliveryDate {
            get {
                return this.expectedDeliveryDateField;
            }
            set {
                this.expectedDeliveryDateField = value;
                this.RaisePropertyChanged("expectedDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedDeliveryDateSpecified {
            get {
                return this.expectedDeliveryDateFieldSpecified;
            }
            set {
                this.expectedDeliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("expectedDeliveryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RespondTo", IsNullable=false)]
        public ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondToRespondTo[] ResponseToArray {
            get {
                return this.responseToArrayField;
            }
            set {
                this.responseToArrayField = value;
                this.RaisePropertyChanged("ResponseToArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string additionalExplanation {
            get {
                return this.additionalExplanationField;
            }
            set {
                this.additionalExplanationField = value;
                this.RaisePropertyChanged("additionalExplanation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool responseRequired {
            get {
                return this.responseRequiredField;
            }
            set {
                this.responseRequiredField = value;
                this.RaisePropertyChanged("responseRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseRequiredSpecified {
            get {
                return this.responseRequiredFieldSpecified;
            }
            set {
                this.responseRequiredFieldSpecified = value;
                this.RaisePropertyChanged("responseRequiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime validTimestamp {
            get {
                return this.validTimestampField;
            }
            set {
                this.validTimestampField = value;
                this.RaisePropertyChanged("validTimestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public enum ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailOrderStatusDetailStatusID {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class ArrayOfGetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondToRespondTo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
        public ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest;
        
        public getOrderStatusDetailsRequest1() {
        }
        
        public getOrderStatusDetailsRequest1(ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest) {
            this.GetOrderStatusDetailsRequest = GetOrderStatusDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
        public ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsResponse GetOrderStatusDetailsResponse;
        
        public getOrderStatusDetailsResponse1() {
        }
        
        public getOrderStatusDetailsResponse1(ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsResponse GetOrderStatusDetailsResponse) {
            this.GetOrderStatusDetailsResponse = GetOrderStatusDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusTypesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
                this.RaisePropertyChanged("wsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusTypesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArrayOfGetOrderStatusTypesResponseStatusStatus[] statusArrayField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
        public ArrayOfGetOrderStatusTypesResponseStatusStatus[] StatusArray {
            get {
                return this.statusArrayField;
            }
            set {
                this.statusArrayField = value;
                this.RaisePropertyChanged("StatusArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class ArrayOfGetOrderStatusTypesResponseStatusStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusTypesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
        public ConsoleApp1.OrderStatusReference.GetOrderStatusTypesRequest GetOrderStatusTypesRequest;
        
        public getOrderStatusTypesRequest1() {
        }
        
        public getOrderStatusTypesRequest1(ConsoleApp1.OrderStatusReference.GetOrderStatusTypesRequest GetOrderStatusTypesRequest) {
            this.GetOrderStatusTypesRequest = GetOrderStatusTypesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusTypesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
        public ConsoleApp1.OrderStatusReference.GetOrderStatusTypesResponse GetOrderStatusTypesResponse;
        
        public getOrderStatusTypesResponse1() {
        }
        
        public getOrderStatusTypesResponse1(ConsoleApp1.OrderStatusReference.GetOrderStatusTypesResponse GetOrderStatusTypesResponse) {
            this.GetOrderStatusTypesResponse = GetOrderStatusTypesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp1.OrderStatusReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp1.OrderStatusReference.IService1>, ConsoleApp1.OrderStatusReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1 ConsoleApp1.OrderStatusReference.IService1.getOrderStatusDetails(ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 request) {
            return base.Channel.getOrderStatusDetails(request);
        }
        
        public ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsResponse getOrderStatusDetails(ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest) {
            ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 inValue = new ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1();
            inValue.GetOrderStatusDetailsRequest = GetOrderStatusDetailsRequest;
            ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1 retVal = ((ConsoleApp1.OrderStatusReference.IService1)(this)).getOrderStatusDetails(inValue);
            return retVal.GetOrderStatusDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1> ConsoleApp1.OrderStatusReference.IService1.getOrderStatusDetailsAsync(ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 request) {
            return base.Channel.getOrderStatusDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusDetailsResponse1> getOrderStatusDetailsAsync(ConsoleApp1.OrderStatusReference.GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest) {
            ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1 inValue = new ConsoleApp1.OrderStatusReference.getOrderStatusDetailsRequest1();
            inValue.GetOrderStatusDetailsRequest = GetOrderStatusDetailsRequest;
            return ((ConsoleApp1.OrderStatusReference.IService1)(this)).getOrderStatusDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1 ConsoleApp1.OrderStatusReference.IService1.getOrderStatusTypes(ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 request) {
            return base.Channel.getOrderStatusTypes(request);
        }
        
        public ConsoleApp1.OrderStatusReference.GetOrderStatusTypesResponse getOrderStatusTypes(ConsoleApp1.OrderStatusReference.GetOrderStatusTypesRequest GetOrderStatusTypesRequest) {
            ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 inValue = new ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1();
            inValue.GetOrderStatusTypesRequest = GetOrderStatusTypesRequest;
            ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1 retVal = ((ConsoleApp1.OrderStatusReference.IService1)(this)).getOrderStatusTypes(inValue);
            return retVal.GetOrderStatusTypesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1> ConsoleApp1.OrderStatusReference.IService1.getOrderStatusTypesAsync(ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 request) {
            return base.Channel.getOrderStatusTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.OrderStatusReference.getOrderStatusTypesResponse1> getOrderStatusTypesAsync(ConsoleApp1.OrderStatusReference.GetOrderStatusTypesRequest GetOrderStatusTypesRequest) {
            ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1 inValue = new ConsoleApp1.OrderStatusReference.getOrderStatusTypesRequest1();
            inValue.GetOrderStatusTypesRequest = GetOrderStatusTypesRequest;
            return ((ConsoleApp1.OrderStatusReference.IService1)(this)).getOrderStatusTypesAsync(inValue);
        }
    }
}
